"""empty message

Revision ID: 798f3c5c42de
Revises: acc49fec832c
Create Date: 2022-02-15 19:20:16.460848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798f3c5c42de'
down_revision = 'acc49fec832c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['voter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
